name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # specify your desired Node.js version

    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20  # Vercel GitHub Action
      with:
        vercel_token: ${{ secrets.VERCEL_TOKEN }}   # Set your Vercel token in GitHub Secrets
        vercel_org_id: ${{ secrets.VERCEL_ORG_ID }} # Vercel Organization ID from your Vercel Dashboard
        vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }} # Vercel Project ID from your Vercel Dashboard
        vercel_dir: '.'  # Set to the root directory of your project

    - name: Vercel Deploy Log
      run: echo "Deployed to Vercel successfully"


       #   with:
    #     vercel_token: 'iEBwhofXuuUagyq7kZ8IM1RT'
    #     vercel_org_id: 'team_YzvZ0DAok6ca08bXsjr9gFiS'
    #     vercel_project_id: 'prj_BGv8BKAZTpTCOFdHB9FJSqF0NS53'
    #     vercel_dir: '.'  # Set to the root directory of your project